package internhub;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import internhub.Company;
import internhub.CompanyRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class CompanyController {
	@Autowired // This means to get the bean called repository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private CompanyRepository repository;

    @GetMapping("/companies")
	public @ResponseBody Iterable<Company> getAllCompanies() {
		// This returns a JSON or XML with the companies
		return repository.findAll();
	}

    @PostMapping("/companies")
    public @ResponseBody String newCompany(@RequestBody Company newCompany) {
        repository.save(newCompany);
        return "good job you saved";
    }

    @GetMapping("/companies/{id}")
    Company one(@PathVariable Long id) {

        return repository.findById(id)
                .orElseThrow(() -> new CompanyNotFoundException(id));
    }

    @PutMapping("/companies/{id}")
    Company replaceCompany(@RequestBody Company newCompany, @PathVariable Long id) {

        return repository.findById(id)
                .map(employee -> {
                    employee.setName(newCompany.getName());
                    employee.setWebsite(newCompany.getWebsite());
                    return repository.save(employee);
                })
                .orElseGet(() -> {
                    newCompany.setId(id);
                    return repository.save(newCompany);
                });
    }

    @DeleteMapping("/companies/{id}")
    void deleteCompany(@PathVariable Long id) {
        repository.deleteById(id);
    }

}
