package internhub;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import internhub.Company;
import internhub.CompanyRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class CompanyController {
	@Autowired // This means to get the bean called repository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private CompanyRepository repository;

	@GetMapping("/add") // Map ONLY GET Requests
	public @ResponseBody String addNewCompany (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Company n = new Company();
		n.setName(name);
		repository.save(n);
		return "Saved";
	}

    @GetMapping("/companies")
	public @ResponseBody Iterable<Company> getAllCompanies() {
		// This returns a JSON or XML with the companies
		return repository.findAll();
	}

    @PostMapping("/companies")
    Company newCompany(@RequestBody Company newCompany) {
        return repository.save(newCompany);
    }

    @GetMapping("/companies/{id}")
    Company one(@PathVariable Long id) {

        return repository.findById(id)
                .orElseThrow(() -> new CompanyNotFoundException(id));
    }

    @PutMapping("/companies/{id}")
    Company replaceCompany(@RequestBody Company newCompany, @PathVariable Long id) {

        return repository.findById(id)
                .map(employee -> {
                    employee.setName(newCompany.getName());
                    return repository.save(employee);
                })
                .orElseGet(() -> {
                    newCompany.setId(id);
                    return repository.save(newCompany);
                });
    }

    @DeleteMapping("/companies/{id}")
    void deleteCompany(@PathVariable Long id) {
        repository.deleteById(id);
    }

}
