package internhub;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import internhub.Position;
import internhub.PositionRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class PositionController {
	@Autowired // This means to get the bean called repository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PositionRepository repository;

    @GetMapping("/position")
	public @ResponseBody Iterable<Position> getAllCompanies() {
		// This returns a JSON or XML with the companies
		return repository.findAll();
	}

    @PostMapping("/position")
    public @ResponseBody String newPosition(@RequestBody Position newPosition) {
        repository.save(newPosition);
        return "good job you saved";
    }

    @GetMapping("/position/{id}")
    Position one(@PathVariable Long id) {

        return repository.findById(id)
                .orElseThrow(() -> new PositionNotFoundException(id));
    }

    @PutMapping("/position/{id}")
    Position replacePosition(@RequestBody Position newPosition, @PathVariable Long id) {

        return repository.findById(id)
            .map(position -> {
                position.setLink(newPosition.getLink());
                position.setCompany(newPosition.getCompany());
                position.setTitle(newPosition.getTitle());
                position.setSeason(newPosition.getSeason());
                position.setYear(newPosition.getYear());
                position.setDegree(newPosition.getDegree());
                position.setLocation(newPosition.getLocation());
                return repository.save(position);
            })
            .orElseGet(() -> {
                newPosition.setId(id);
                return repository.save(newPosition);
            });
    }

    @DeleteMapping("/position/{id}")
    void deleteCompany(@PathVariable Long id) {
        repository.deleteById(id);
    }

}
